# This is a basic workflow to help you get started with Actions

name: JS Actions

on: [push]
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
